electron/apps

package.json

This will prevent confusion for any users of node <4, as the `npm install` step will fail with a message about the node version.

require node 4 or greater

---

package.json
test/build.js
test/data.js

The existing test verify the structure and content of the metadata and icon files in the `apps` directory. 
These new tests verify that the `require`able `index.json` file produced by the build script is intact and has all the expected metadata.

test the build

---

test/data.js

Users sometimes include an icon file that has the proper dimensions, but is not properly named. The test suite was showing errors like "icon must be a square" not because the icon wasn't sqaure, but because the target filename didn't exist. Example: https://github.com/electron/electron-apps/pull/46
If the icon file is not found, skip these tests using mocha's built-in `this.skip()` feature.
cc @MedZed

skip icon dimensions tests if file doesn't exist

---

.gitignore
.travis.yml
package.json
script/build.js
script/resize.js
test/data.js

There are 6.5 MB worth of icons on [electron.atom.io/apps/](http://electron.atom.io/apps)
This PR adds a script that resizes all the app icons to various smaller dimensions: 32, 64, 128.
To keep the repo small and free of auto-generated content, this new resize script is run in an npm postinstall hook:
```
$ npm install electron/electron-apps
$ tree node_modules/electron-apps/apps     
node_modules/electron-apps/apps
├── 1clipboard
│   ├── 1clipboard-icon-128.png
│   ├── 1clipboard-icon-32.png
│   ├── 1clipboard-icon-64.png
│   ├── 1clipboard-icon.png
│   └── 1clipboard.yml
...
```
We can shave off 5 MB by using the 64x64 images on the apps page:
```
❯ du -hc apps/**/*icon.png | grep total
6.5M	total
❯ du -hc apps/**/*64.png | grep total
1.5M	total
```
Even if we use 128px icons we can …

Resize app icons at install time

---

apps/caprine/caprine.yml
apps/papyrus/papyrus.yml
apps/ramme/ramme.yml
apps/slack-catchup/slack-catchup.yml
apps/youtube-mp3/youtube-mp3.yml

I have consulted with our legal team, and they have advised us to disallow apps that are using the names of other companies or icons that we find too similar to the logos of other companies without verifying their permission to do so.
That said, we would love to continue featuring all of these apps on our site. If you are an author of one of these apps and would like to see it on the site again, please open a PR that updates the icon file and removes the `disabled: true` line from the app's yml file.
Apologies for the inconvenience, and thanks for your understanding.
cc @terkelg @sindresorhus @MedZed @morkro

disable apps using company logos without permission

---

apps/jukeboks/jukeboks.yml

Hi, @zeke. I'm sorry, I mistake to write name  space as author name.
I rename project name

Rename author name to project name

---

script/resize.js

🔕
278 icons * 3 resizes each == too much output.
```
ionic-lab-icon-64.png
jasper-icon-64.png
jukeboks-icon-64.png
jibo-icon-64.png
kaku-icon-64.png
kakapo-icon-64.png
kap-icon-64.png
kongdash-icon-64.png
keeweb-icon-64.png
kitematic-icon-64.png
laverna-icon-64.png
ling-icon-64.png
light-table-icon-64.png
lightgallery-icon-64.png
losslesscut-icon-64.png
makeappicon-desktop-icon-64.png
manageyum-icon-64.png
mapbox-icon-64.png
mancy-icon-64.png
markdownify-icon-64.png
marp-icon-64.png
mdnote-icon-64.png
medley-icon-64.png
mattermost-icon-64.png
```

do not log every resized filename

---

package.json
scripts/release.sh
test/human-data.js
test/machine-data.js

Basic app info is added by **humans**, and extra info is later filled in by a **bot**.
Humans edit the contents of the `/apps` directory, adding basic data
and an icon for each app. When a pull request is opened on this repo, the CI
service tests that the data in the `/apps` directory is complete.
A bot periodically clones this repository and does some extra work:
- collecting app submission dates from git history
- resizing icons
- extracting color palettes from icons ([WIP branch](https://github.com/electron/electron-apps/tree/colors))
This PR begins to formally separate those two concerns.

distinguish human tests from bot tests

---

package.json
script/clean.js

`npm run build` wasn't working on machine after some apps were removed. This adds a cleanup step to the build process to ensure removed apps are fully removed.

add script for cleaning leftover build artifacts

---

script/dates.js

This typo was breaking the build process, but it wasn't picked up by CI.
One of the perils of only using CI to test [human-generated content](https://github.com/electron/electron-apps/blob/aacf8bf73a68a99d74b8b0c8189c9998f7b98257/package.json#L12-L13).

fix broken reference to slug

---

scripts/release.sh

New releases are not properly being associated with @electron-bot, presumably because the git configured email address is wrong:

use the right email for electron-bot

---

scripts/release.sh

Every so often (twice now) the release script will successfully publish a new version to npm, but the following `git push` will fail, leaving github out of sync with npm and preventing new versions from publishing. This PR works around the problem by git pushing first, then npm publishing.
Also, a minor change to the way git author is specified.

tweak release script

---

test/human-data.js

These tests assert that every app (that has screenshots) has valid screenshot metadata, like a fully qualified HTTPS URL for the image, and a fully-qualified URL for the link, if present.
Waiting for Xcode to install, so haven't tested this locally yet. 🤞

add tests for screenshot metadata

---

script/release.sh

Seeing this in the build script output:
```
++ git status --porcelain
+ [[ -n '' ]]
+ exit
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-apps@1.1648.0 release: `script/release.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-apps@1.1648.0 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2017-07-21T15_34_58_083Z-debug.log
```
But this is not an error situation. It just means that there's nothing to commit and the release script should just exit. Maybe adding an explicit exit code will solve this.

make release script exit successfully when git is clean

---

apps/appear-in/appear-in.yml
apps/bitbloq/bitbloq.yml
apps/colorpicker/colorpicker.yml
apps/criptio/criptio.yml
apps/egret-wing/egret-wing.yml
apps/franz/franz.yml
apps/glyphr-studio/glyphr-studio.yml
apps/groupme/groupme.yml
apps/headlines/headlines.yml
apps/now/now.yml
apps/paws-for-trello/paws-for-trello.yml
apps/pencil/pencil.yml
apps/preserver/preserver.yml
apps/qmui-web/qmui-web.yml
apps/socialcast/socialcast.yml
apps/soundnode/soundnode.yml
apps/timetable/timetable.yml
apps/vagrant-manager/vagrant-manager.yml
apps/yout/yout.yml
test/human-data.js

This PR adds a test that verifies that app descriptions don't start with the name of the app itself. This works for single-word as well as multi-word app names.
It also cleans up all existing apps that were in violation of that rule. :)

description cannot start with app name

---

test/human-data.js

Just got a PR that has `keywords` as a string instead of an array: https://github.com/electron/electron-apps/pull/243
This PR adds a test to check that `keywords` is an array, if it exists.

test that keywords is an array if present

---

script/dates.js

I noticed that the build+release process slowed down considerably because of the code that was looking through the (large) git history to find app submission dates. Now that we are caught up on dates and no longer applying them retroactively to apps submitted in the past, we can always just apply the current day as the date. This should speed things up again. 🚀

set app submission date to today

---

lib/apps-with-github-repos.js
package-lock.json
package.json
script/pack.js
script/readmes.js
script/releases.js
test/machine-data.js

This PR turns GitHub Releases and README fetching back on!
I updated it to use the [bottleneck](http://ghub.io/bottleneck) package, which gives us control over API request concurrency. It's currently set to `4` concurrent requests, and all 200ish releases and readmes download in under 20 seconds on my machine.
For apps that have a GitHub repo:
- `latestRelease` is the pure object we got from GitHub. No tampering. (cc @MarshallOfSound whose Fedora assets were getting stripped out)
- `readmeOriginal` is what we got from GitHub
- `readmeCleaned` has relative image URLs made absolute
- `latestReleaseFetchedAt` and `readmeFetchedAt` timestamps ensure we don't fetch too often: data is fetched at most once every 4 hours per app
cc @jkleinsc

Fetch GitHub release data again

---

apps/google-play-music-desktop-player/google-play-music-desktop-player.yml
contributing.md
package-lock.json
package.json
test/human-data.js

The [pick-a-good-color](https://github.com/zeke/pick-a-good-color) module will always pick an accessible color, but sometimes the color just doesn't look quite right.
To work around this, #325 enabled app developers to choose their own colors. This PR is a followup that ensures sure the human-provided colors are in fact accessible according to the [WCAG guidelines](https://www.w3.org/TR/WCAG/#visual-audio-contrast)..
When a color's contrast ratio is not high enough, this kind of error is produced:
```
AssertionError: google-play-music-desktop-player: contrast ratio too low for goodColorOnWhite. Try: #DE2811
```
cc @MarshallOfSound. I took the liberty of adding custom colors for GPMDP as a test case, based on the icon and the website.
cc @codebytere

Accessible Color Warnings

---

apps/atom/atom.yml
apps/figma/figma.yml
apps/github-desktop/github-desktop.yml
apps/hyper/hyper.yml
apps/simplenote/simplenote.yml
apps/slack/slack.yml
apps/visual-studio-code/visual-studio-code.yml
apps/webtorrent/webtorrent.yml
contributing.md

Many Electron apps are published to homebrew so macOS users can install them on the command line like `brew cask install hyper`. Let's display these on the website!

Add Homebrew Cask Names

---

apps/webtorrent/webtorrent.yml

This will make Webtorrent download links, release notes, and other goodies show up on https://electronjs.org/apps/webtorrent
cc @feross

add webtorrent repository url

---

contributing.md
meta/colors.json
package.json
readme.md
script/colors.js
script/pack.js
test/machine-data.js

Moving the responsibility of https://github.com/electron/electron.atom.io/pull/832 over to this module.
The pink below is an example of the `faintColorOnWhite` for Webtorrent:

Faint colors

---

script/pack.js
test/human-data.js

If an app has a `website` and a `repository` and they're both effectively the same URL, then `website` is removed (in the published module).
Fixes #367

avoid redundant website and repo urls

---

apps/webtorrent/webtorrent.yml

Just a small fix of Webtorrent desktop's repository url.

Fix webtorrent-desktop repository url

---

apps/discord/discord.yml

I believe Discord belongs in 'Social Networking' because it is technically a social network for gaming, not a game itself.

Put Discord in Social Networking

---

contributing.md

A followup to https://github.com/electron/electronjs.org/issues/1149

document app removal process

---

.travis.yml

Followup to #591.
Node.js v4 is reaching End of Life this month. https://github.com/nodejs/Release/tree/643af71ee8365efbdccaa134690425ea05931279#release-schedule

only test with node 8 on travis

---

script/pack.js
script/resize.js
test/machine-data.js

This is a followup to #591 and https://github.com/electron/electronjs.org/pull/999 so we can show bigger icons in the sidebar.

generate 256px resized icons

---

apps/signal/signal.yml

We recently renamed our GitHub organization. This change updates the URL of our repository.

Update Signal Messenger repository URL

---

apps/octopi-init/octopi-init.yml

Unfortunately, the yaml file is a snapshot in time and doesn't reflect the latest/greatest download link(s). It was necessary to create a separate `electron_README.md` as an endpoint.

Updated octopi-init.yml

---

apps/thunder/thunder.yml

As mentioned in https://github.com/electron/apps/issues/602:
> The app [Thunder](https://electronjs.org/apps/thunder) seems to be outdated as it’s unreachable and I couldn’t find further info anywhere.
> 
> According to whois.net, the domain trollswebapp.com expired 2 days ago. I couldn’t find the icon or description anywhere else either.
> 
> cc @davidsolorzano20 who added it with https://github.com/electron/apps/pull/214

Disable Thunder app, ref #602

---

test/colors-spec.js

The test is timing out without any further error information. Example: https://github.com/electron/apps/issues/798
Increase the timeout to test the theory that it's just a slow box running the tests, rather than some other kind of problem.

chore: increase color test timeout

---

package.json
readme.md

Fixed the link in Travis CI. Was previously pointing at a non-existent page (probably because of repository renaming).
Also: update repository URL in package.json

fix: Travis CI link in readme

---

test/colors-spec.js
test/human-data.js

Try to make test output more readable on failure.
- try to make the icon-must-be-within-these-dimensions error message more readable
- capture & test the `console.info()` messages from the complimentary color generation pass, since that fills up the console with noise that takes focus away from error messages

More readable test warnings

---

apps/ao/ao.yml
apps/tusk/tusk.yml

A minor fix, that updates the links pointing to media assets, repositories and websites related to the [**Ao**](https://github.com/klaussinani/ao) and [**Tusk**](https://github.com/klaussinani/tusk) apps. Please feel free to suggest any changes : )

fix: update asset links for `Ao` & `Tusk` apps

---

apps/bunqdesktop/bunqdesktop.yml

Some of the information is outdated and I added some missing fields like the license and snapcraft name
Related issue bunqCommunity/bunqDesktop#443

feat: Add and correct bunqDesktop information

---

package-lock.json
package.json

This tag got created: https://github.com/electron/apps/releases/tag/v1.5779.0
but the version in `package.json` wasn't correspondingly updated. This PR does that.
/cc @BinaryMuse

fix: version should be 1.5779.0

---

apps/insomnia/insomnia.yml

License is changed from AGPL to MIT since getinsomnia/insomnia@3db00f5.

Update insomnia license

---

script/releases.js
test/machine-data.js

Previously, `script/releases.js` was writing an output hash to disk that did not contain apps that did not need their release data refreshed. This PR ensures those apps are also included in the output hash. It also adds a test to ensure that no app with a repo is missing from the releases data.

 fix: ensure apps with up-to-date release data is not deleted

---

package-lock.json
package.json
script/release.sh
test/colors-spec.js

Closes #802 
Fixes #804 
If we push code changes before tags we will either
* Fail to push code and therefore no tags will be pushed so no conflict
* Succeed in pushing code and regardless of whether the tag is pushed there will be no conflict as it will bump correctly the next time
The tests failed because of #804 so I decided to fix that in this PR

fix: push version bump before tags

---

playbook/closed-source-needs-evidence.md
playbook/possible-trademark-issue.md

Adds canned responses for two evergreen issues:
1. Closed-source apps which don't provide evidence that they use Electron
2. Possible trademark issues

chore: add playbook

---

apps/move-more/move-more.yml

Changed the screenshots to ones that fit the width and height ratio used on https://electronjs.org/apps/move-more
old: https://deskrelief.co.uk/img/feature/feature-2.jpg (app only screenshot)
new: https://deskrelief.co.uk/screenshots/2.jpg (full screen 16:9 ratio)

fix: Update Move More app screenshots

---

package.json

Yeah, node 10/12 should totally be allowed to consume this module 👍

fix: allow any node version higher than 8

---

apps/brave-browser/brave-browser.yml

Not sure if this is allowed because this is not my app, but Brave Browser stopped using their Electron fork (Muon) last year. They now use Chromium directly.
This PR adds the `disabled` flag on their app.
See: https://brave.com/brave-upgrades/

chore: disable Brave Browser

---

.github/workflows/pull_request.yml

Because the apps repo has a lot of binary files and churn, it takes about three minutes to get a snapshot ready to run CI on. ([example CI run](https://github.com/electron/apps/pull/1191/checks?check_run_id=230321354))
This PR limits the fetch depth in hopes of speeding that up. ([documentation](https://github.com/actions/checkout/blob/master/action.yml), [code example](https://github.com/marketplace/actions/markdown-link-check))
Looks like we might've been hitting this overhead before the Actions migration, too?

feat: use a shallow fetch when pulling code for CI

---

apps/fnew-desktop/fnew-desktop.yml

FNew has moved to org:0810-software and has gotten its own domain: https://fnew-social.net

chore: Change fnew-desktop.yml

---

apps/ueli/ueli.yml

This PR updates the URL to [ueli](https://github.com/oliverschwendener/ueli)'s [website](https://ueli.app).

feat: Updated website URL for ueli

---

apps/twinkle-tray/twinkle-tray.yml

Screenshot was not included in the original yml.

fix: Twinkle Tray screenshot

---

lib/raw-app-list.js
package-lock.json
package.json
script/pack.js
test/human-data.js

This PR updates the `yaml` parser from `yamljs` to `js-yaml` what's work more flexible and has more understandable error reporting. `yamljs` still used in places where need some more work to migrate.

feat: use js-yaml instead of yamljs

---

apps/teamsql/teamsql.yml

See the comment on the disable flag - unfortunately this doesn't seem to be available anymore.
The TeamSQL website redirects to [DataRow](https://datarow.com/) (they rebranded) where they explain the move to AWS, the TeamSQL app isn't available anymore.

feat: Disable TeamSQL

---

apps/voltra/voltra.yml

Voltra is sadly not available anymore: https://twitter.com/voltraco/status/1123153090251771905
The homepage is offline along with the blog post, that explained, that voltra stopped development...

docs: discontinue notice

---

apps/wavebox/wavebox.yml

Wavebox is now built on Chromium

feat: Disable Wavebox

---

apps/checksum-validator/checksum-validator.yml
apps/hain/hain.yml
apps/odio/odio.yml
apps/punk/punk.yml
apps/sandman/sandman.yml

>  many apps are now broken or no longer working, and thus should be removed from our directories
---
I just found 5 apps that are using the old versions of electron, or their website link is no longer working,
so i disabled them
Please check my pull request and if you have any feedback please let me know 😄 !
Thanks.

fix: Remove broken or deprecated apps

---

apps/snailfm/snailfm.yml
lib/raw-app-list.js
script/pack.js
script/resize.js

Fixes #1856
I found out that the SnailFM app was the culprit here due to an error processing the PNG file. I've disabled it and prevented all disabled apps from being processed in the build scripts.
cc @snaildos

fix: disable broken app and add safeguards

---

apps/booker/booker.yml

Work on Booker was discontinued. So it has to be disabled.

chore: disable Booker app

---

script/readmes.js

Images from GitHub repositories are blocked because of the server's CORS headers:
This PR should fix these errors.
See #1989

fix: cors errors on images from github repos

---

apps/display-dj/display-dj.yml

Fix typo: The app's name was wrong!

chore: display-dj.yml: Fix typo

---

script/release.sh

Right now the repo was cloned by [actions/checkout@v3](https://github.com/electron/apps/blob/dee0bd804fc7ad76e634ab2b630a48c5c9bfbf83/.github/workflows/schedule.yml#L12) as well as inside the `release.sh` script which was leading to [](url)
Removed the redundant cloning of the repo inside the `release.sh` script

fix: update and release pipeline

---

readme.md

Status badge for the schedule job (which is unfortunately failing at the moment).

docs: add status badge to README.md

---

.github/semantic.yml

No longer used since switching to `.github/workflows/semantic.yml`.

ci: remove unused GitHub app config file
