electron/apps

wizard.js

catch errors from inquirer in wizard

---

apps/etcher/etcher.yml

A followup to https://github.com/electron/electron.atom.io/pull/608

update etcher slogan

---

apps/healthi/healthi.yml

Change healthi app webpage

---

contributing.md

Hopefully this will be reasonably clear.

Add notes about trademarks to contributing guide

---

apps/jasper/jasper.yml

I will change the description more better.

change description of Jasper

---

readme.md

This PR adds a section to the README explaining the roles of humans and bots in the creation of the `electron-apps` package.
Rendered: https://github.com/electron/electron-apps/blob/d9175fef92dc941a3501e1ccd190fba227cfb9ec/readme.md

How it Works

---

lib/raw-app-list.js
script/colors.js

prevent superficial diffs in colors.json

---

package.json
scripts/release.sh

This PR fixes a couple of hiccups in the current release process.

Fix some release details

---

package.json

allow node 6 or greater

---

apps/colol/colol.yml

Edit colol

---

contributing.md

Adding this section to contributing so I can link users to it when needed.

document locales

---

package.json
script/pack.js
script/release.sh
script/releases.js

Don't fetch any single app's release data more than once every 24 hours.

Relax release fetching

---

apps/google-play-music-desktop-player/google-play-music-desktop-player.yml

Just a quick update of metadata for GPMDP

Update GPMDP meta data

---

contributing.md

This PR is an attempt to create a re-usable blurb to which we can direct future contributors.

add a note about proper use of logos and company names

---

script/dates.js

standardize

---

contributing.md
test/human-data.js

Support YouTube property in app metadata

---

apps/zeplin/zeplin.yml

disable zeplin

---

apps/https-checker/https-checker.yml

Hey, I'd like to resubmit HTTPS Checker, looks like it's currently disable due to a broken link (we moved sites) but this fixes that and adds keywords for it.
Hope this is ok.

Added HTTPS Checker back in (fixing broken link)

---

apps/perlotto/perlotto.yml

Perlotto app got new functionality recently, now
it's able to handle youtube as well. This commit updates
the description to mention this fact.

Perlotto app - update description to include new functionality

---

.npmignore

Fixes `require('electron-apps/categories')`

do not npmignore meta dir

---

script/releases.js
test/machine-data.js

Followup to #300 
cc @jkleinsc

add tests for readme data

---

apps/ao/ao.yml

Ao is an unofficial Microsoft To-do desktop app with a couple of useful features.
**Homepage** https://klauscfhq.github.io/ao
**Repository** https://github.com/klauscfhq/ao
Awesome list ❤

Add Ao app

---

apps/nylas-n1/nylas-n1.yml

Nylas is shutting down or something.
cc @bengotow

disable nylas

---

script/releases.js

Add fedora package extension

---

apps/tusk/tusk.yml

Minor update for the Tusk app : )
- Updated broken links
- Added screenshots & captions
Update: Fixes #324

Tusk update

---

apps/google-play-music-desktop-player/google-play-music-desktop-player.yml

Add the screenshot from the README.
cc @MarshallOfSound

update gdmdp screenshot

---

apps/dat/dat.yml

add dat screenshot

---

apps/webtorrent/webtorrent.yml

update webtorrent data

---

apps/laverna/laverna.yml

Here's how it looks like for me: https://i.imgur.com/7FSvUJx.png

Fixed typo

---

apps/github-desktop/github-desktop.yml

See https://github.com/desktop/desktop/pull/3139 for more details

the cask name has been updated

---

apps/insomnia/insomnia.yml

This PR updates the metadata for [Insomnia](https://insomnia.rest) to include a screenshot, license, and Homebrew cask name.
P.S. Loving the new Electron website. Congrats and nice work!

Update meta information for Insomnia

---

apps/coypu/coypu.yml

So I added link to the repository and license.

Coypu is now an open source app

---

apps/beaker-browser/beaker-browser.yml

add homebrew cask name to beaker

---

apps/serina/serina.yml

Hello, I'm changing the category for my Serina application

Changed category to app Serina

---

apps/time-zone-converter/time-zone-converter.yml

Hi! 
I've fixed App Name and added a screenshot.
Can you update our page? 
Thanks!

Add screenshot + Change Title

---

apps/unofficial-zalo/unofficial-zalo.yml

URL: [Unofficial Zalo new homepage](https://ansidev.xyz/)

Change homepage

---

script/readmes.js
test/machine-data.js

Do what we do for images but for links as well 👍

Resolve relative links

---

apps/elcalc/elcalc.yml

Just changed the link to elcalc app 😄

Updated elcalc app

---

apps/nfov/nfov.yml

Add homebrewCask name to nfov

---

apps/fastlane/fastlane.yml

I've got ERR_CONNECTION_REFUSED on https://fastlaneapp.co/ but http worked fine.

fix broken link

---

apps/storm/storm.yml

Add GitHub repo where releases are stored

---

apps/audionodes/audionodes.yml

This is how it should've been initially, my apologies for missing this one.

changed name from lowercase to CamelCase

---

apps/patchwork/patchwork.yml

add p2p keyword to patchwork

---

apps/rename-multiple-file/rename-multiple-file.yml

update description for rename-multiple-file

---

apps/zeplin/zeplin.yml

Re-enable Zeplin per https://github.com/electron/electron-apps/issues/272#issuecomment-368147294

Re-enable Zeplin

---

apps/multiple-file-manager/multiple-file-manager.yml

multiple file manager: change rename to modify

---

apps/tweeten/tweeten.yml

Update Tweeten website

---

apps/code-rpgify/code-rpgify.yml

Remove Code RPGify

---

apps/janus-workspace/janus-workspace.yml

Remove private repo link

---

apps/picpipe/picpipe.yml

The all was already submitted I have changed a description and added screenshots.

changed description and added screenshots.

---

apps/unofficial-zalo/unofficial-zalo.yml

I 've updated English version link for Unofficial Zalo homepage.

Update English version link for Unofficial Zalo homepage

---

apps/joplin/joplin.yml

I have updated the links to use https and to all use the same domain, and I've updated the list of supported languages.

Updated Joplin spec

---

apps/visual-studio-code/visual-studio-code.yml

At least the released binary and the logo is not MIT

Revise license line

---

apps/colol/colol.yml

disable colol

---

apps/mmrcalculator/mmrcalculator.yml

Updated description & keywords

Updated description & keywords

---

apps/missive/missive.yml

Updated Missive App with homebrewCaskName

Updated Missive App with homebrewCaskName

---

apps/electorrent/electorrent.yml

Updated Electorrent App with homebrewCaskName

Updated Electorrent App with homebrewCaskName

---

apps/catlight/catlight.yml

Updated catlight App with homebrewCaskName

Updated catlight App with homebrewCaskName

---

apps/lightgallery/lightgallery.yml

Updated lightgallery App with homebrewCaskName

Updated lightgallery App with homebrewCaskName

---

package-lock.json
package.json

I have updated the screenshots of Laravel Kit.
https://github.com/tarequemdhanif/laravel-kit
https://electronjs.org/apps/laravel-kit

Update Laravel Kit screenshots

---

apps/ueli/ueli.yml

Updated app "ueli":
* Updated description and keywords to match the latest version
* Removed screenshot because the project's readme already contains example screenshots

Updated app "ueli"

---

apps/video-hub-app/video-hub-app.yml

Just updating the images for the app 😄

Video Hub App images added

---

apps/vagrant-manager/vagrant-manager.yml

Updated: Vagrant Manager
Now with OSX, Windows & Debian builds
Translated into 9 languages

Update Vagrant Manager

---

contributing.md
readme.md

This PR cleans up the README a bit and adds a section about releases to the contributing doc, so folks know how long to expect to wait before their changes are reflected on the website.
Resolves #395

Document release schedule

---

apps/protegopdf/protegopdf.yml

update protegopdf app

---

apps/r6rc/r6rc.yml

Changed repository link and website link.

Current version as of 7/23/18

---

contributing.md

Fixes #475
fyi @zeke, apps who described in #475 not found in `apps` folder.

feat: add npmPackageName property

---

apps/dixa/dixa.yml

Just on update for Dixa app with repo and description + one keyword

feat: add a repo for the dixa app

---

apps/museeks/museeks.yml

I recently changed my username on Github, because GH is smart and forward URLs nicely, it's fine, but making the change just in case :)

chore: update username of Museeks maintainer

---

apps/figma/figma.yml

I think the category should be changed from **Photo & Video** to **Graphics & Design** - it's a UX design tool after all

fix: Fix category for Figma

---

apps/doki-doki-mod-manager/doki-doki-mod-manager.yml

This PR adds a link to the GitHub repository.

fix: Update doki-doki-mod-manager.yml

---

apps/lbry-desktop/lbry-desktop.yml

rename lbry-desktop to LBRY Desktop

fix: Update lbry-desktop.yml

---

apps/alva/alva.yml

Removed unnecessary comma added in #817 and broke the tests.
Fixes #823 
/cc @ckerr

fix: removing unnecessary comma for fixing tests.

---

apps/hyper/hyper.yml

Fixing 404 Error for GIF Preview

fix: solve 404 error for Hyper App GIF

---

apps/unicode-plus/unicode-plus.yml

feat: Updated Unicode Plus description and keywords

---

apps/e-mage/e-mage.yml

chore: update e-mage.yml

---

apps/altair/altair.yml

chore: update homebrewCaskName in altair.yml

---

apps/mockoon/mockoon.yml

fix: correct Mockoon's screenshot URL

---

contributing.md

A few submissions have bumped up against this recently, so make the rules a little clearer.
CC @BinaryMuse @codebytere

docs: clarify rules on use of company and product names

---

readme.md

electron.atom.io => electronjs.org
/cc @BinaryMuse

chore: fix site link

---

apps/thunderdocs/thunderdocs.yml

fix: Update information about "ThunderDocs"

---

apps/y2mp3/y2mp3.yml

App supports now (v1.1.0) single video too

chore: update y2mp3

---

apps/playcode/playcode.yml

Change `meadowcottage` to  `playcode`

chore: update 'playcode' author

---

apps/webnet/webnet.yml

chore: update webnet.yml

---

package.json

Changed mocha reporter from spec to min for show only errors.

test: change mocha reporter from spec to min

---

apps/gitmoji/gitmoji.yml

Change `Meadowcottage` to `carloscuesta`.
I change `imageUrl` but it is not exist.

chore: update 'carloscuesta' author

---

apps/ao/ao.yml
apps/bdash/bdash.yml
apps/caption/caption.yml
apps/devrantron/devrantron.yml
apps/dext/dext.yml
apps/freeman/freeman.yml
apps/i18n-manager/i18n-manager.yml
apps/ionic-creator/ionic-creator.yml
apps/jasper/jasper.yml
apps/luna/luna.yml
apps/markdownify/markdownify.yml
apps/marktext/marktext.yml
apps/odrive/odrive.yml
apps/spotspot/spotspot.yml
apps/system-designer/system-designer.yml
apps/thomas/thomas.yml
apps/tusk/tusk.yml
apps/vagrant-manager/vagrant-manager.yml
apps/voltra/voltra.yml
apps/webcatalog/webcatalog.yml

I find 404 link to fix it, but I can't find some url.

chore: update url of image or author

---

apps/tagspaces/tagspaces.yml

chore: update 'TagSpaces' info

---

apps/magiccap/magiccap.yml

Sorry for such a instant PR after the initial but I decided to move it to its own organisation.

feat: Change the repository from JakeMakesStuff/MagicCap to MagicCap/MagicCap

---

apps/waiterio-restaurant-pos/waiterio-restaurant-pos.yml

Add Waiterio Restaurant POS app for macOS and Windows
You can find more info at [www.waiterio.com](https://www.waiterio.com)

feat: add 'Waiterio' app

---

apps/popsql/popsql.yml

fix: Update website for PopSQL

---

apps/vocare-helpdesk/vocare-helpdesk.yml

Disable the vocare-helpdesk app since it no longer uses electron.

Disable vocare-helpdesk

---

apps/wire/wire.yml

Synced from [`wireapp/wire-desktop/electron/package.json`](https://github.com/wireapp/wire-desktop/blob/master/electron/package.json#L29).

docs(wire): Update description

---

apps/cleaver/cleaver.yml

App URL: https://getcleaver.com
Screenshots:

chore: fix Cleaver app screenshots

---

apps/y2mp3/y2mp3.yml

Some features are added so now the app is supporting not just mp3s

chore: Update y2mp3 app's screenshots and description

---

apps/multiple-file-manager/multiple-file-manager.yml

this pull request is change the description to this apps. Because started from this release, application will support on multiple operating system platform.

fix: multiple file manager, change description

---

apps/webcatalog/webcatalog.yml

- update url from outdated link to https://getwebcatalog.com.
- update description to match the current one.
- update screenshots, as shown on https://getwebcatalog.com.

fix: webcatalog.yml url, description and screenshots

---

apps/foda/foda.yml

fix: correct broken image url in foda.yml

---

apps/domain-book/domain-book.yml
apps/voipstudio/voipstudio.yml

fix: metadata tests

---

package-lock.json

Addresses js-yaml and lodash vulnerabilities.

chore: address security vulnerabilities

---

apps/musicplus/musicplus.yml

https://github.com/musicplusapp/musicplus link not working.

feat: Remove 404  Github link

---

apps/aalarm/aalarm.yml

http://api.fridaytec.com/site not working.

feat: Remove 404 website URL

---

apps/basecamp-3/basecamp-3.yml

Updates to existing app in this directory.
Includes screenshots of [Basecamp's core features](https://basecamp.com/features), an updated description and link, addition of relevant keywords, and inclusion of `youtube_video_url`.

fix: Update Basecamp 3 app page

---

apps/dusk-player/dusk-player.yml

Recently added Light mode to the player and so I added a screenshot for it

feat: Add new screenshot for Dusk Player

---

apps/thismypc/thismypc.yml

@ckerr  Change old image positions and add new  gif animations

feat: Update YML file

---

.github/workflows/pull_request.yml
.github/workflows/push.yml

previously, two of them were both named "build".

chore: make workflow names unique

---

apps/kongdash/kongdash.yml

chore: update website address to kongdash.xyz

---

.github/workflows/schedule.yml

It's now private, switched to using node.

build: drop using actions/npm

---

apps/violin/violin.yml

Hello! I've added a screenshot to my app and also replaced the old domain by the new one.

docs: added screenshot to Violin and changed domain.

---

apps/multiple-file-manager/multiple-file-manager.yml

docs: change support operating system, remove macs for now

---

lib/github.js
package-lock.json
package.json
script/publish-to-gh.js
script/release.sh

This thing needed for easily taking metrics for the dist size of the archive.

chore: upload the npm archive to gh releases

---

apps/graviton-editor/graviton-editor.yml

fix: Enable Graviton Editor app

---

apps/discord/discord.yml

Updated the URL for Discord from [discordapp.com](discordapp.com) to the new one [discord.com](discord.com)

fix: Updated URL for Discord

---

apps/opencomic/opencomic.yml

feat: update opencomic screenshots

---

apps/arena/arena.yml

Not my app, but noticed two typos and fixed them.
`buliding` -> `building`
`website` -> `websites`

Fix: fix typos

---

apps/netron/netron.yml

fix: update netron.yml description

---

apps/bearychat/bearychat.yml
apps/gf-trader/gf-trader.yml
apps/pupafm/pupafm.yml
apps/zlilith/zlilith.yml
apps/zneon/zneon.yml

fix: Disable 5 broken and deprecated apps.

---

apps/compress/compress.yml

Updating Compress's screenshots.

feat: Update compress.yml

---

apps/visual-studio-code/visual-studio-code.yml

chore: add VSC screenshot

---

apps/covid-19-cases-overview/covid-19-cases-overview.yml

fix: new version (1.0.0) screenshot.

fix: new screenshot

---

apps/developer-tools/developer-tools.yml

hi there,
i recently added my app in electron apps
but the image URL was incorrect so i just updated it
thanks

feat: Fix developer tools image link

---

apps/runjs/runjs.yml

docs: update runjs description and url

---

apps/raven-reader/raven-reader.yml

chore: Update raven reader repo url

---

apps/station/station.yml

Update Station URL to match our new domain

feat: update Station URL to match our new domain

---

apps/dot/dot.yml

feat: disable dot browser

---

apps/browserosaurus/browserosaurus.yml

- Update website URL.
- Update keywords.

feat: update browserosaurus.yml

---

apps/animeback/animeback.yml

feat: update animeback

---

apps/seobrowse/seobrowse.yml

Added github repository reference.

feat: Update SEOBrowse

---

apps/colorpicker/colorpicker.yml

feat: update description

---

apps/sftpclient/sftpclient.yml

chore: update sftpclient.yml download link

---

apps/morgen/morgen.yml

feat: update Morgen.yml - fix a typo

---

apps/standard-notes/standard-notes.yml

chore: edit standard-notes.yml

---

apps/dbgate/dbgate.yml

update of description and screenshot

fix: dbgate app update

---

apps/abricotine/abricotine.yml

Author recommends others, two of which are Electron projects.

fix: Abricotine is discontinued

---

.github/CODEOWNERS
package.json

Update ownership of electron/apps to me.
I see a lot of ping of users to Zeke and it shouldn't be the case here.

chore: update repo maintainer

---

apps/wallapatta/wallapatta.yml

See the screenshot at https://www.electronjs.org/apps/wallapatta

fix: Wallapatta is abandoned

---

apps/crossover/crossover.yml

chore: update CrossOver license

---

apps/webkitty/webkitty.yml

Just changed the description and added some screenshots for WebKitty, the app I recently submitted.

feat: update WebKitty marketing

---

apps/remindr/remindr.yml

Removed 'open-source' tag. Was not accurate.

feat: Update Remindr .yml file (app already submitted)

---

apps/e-search/e-search.yml

update description and locales
App already submitted. Update description and add locales.

feat: Update e-search.yml file (app already submitted)

---

apps/webkitty/webkitty.yml

I just changed the YML file for the app I submitted a while back.

feat: Update WebKitty website URL & screenshots

---

apps/strimio/strimio.yml

ref https://github.com/electron/apps/issues/2037

chore: disable strimio

---

apps/banana-cake-pop/banana-cake-pop.yml

Changed the application name to improve the visibility when searching for GraphQL.

fix: change app name

---

apps/strimio/strimio.yml

The app is back, updating information, thanks!
Strimio is a free media player for macOS, Windows, and Linux, that enables you to play and organize your live streams like never before.
https://strimio.com

fix: Strimio

---

readme.md

docs: fix CI status badge

---

readme.md

We do not accept anymore new app PR for the moment, we are currently reworking the organisation of this repository.

chore: Update readme.md to not accept new apps

---

.github/workflows/schedule.yml
package-lock.json
package.json

Should fix the failing scheduled workflow.

chore: downgrade imagemin for release workflow
